### ISSUE TITLE
Broken logic for bisecting

### ISSUE THREAD

**Issue by jvook** [Helios747/DolphinBisectTool#12]
The logic of the dropdowns are reversed. Top drop down asks for oldest version and bottom asks for newest version, but the program gives an error and expects them the other way. 

Unfortunately this makes the program not work at all. I put in "Select a build before the issue occurred" -- 5.0-2690; "Select a build where you saw the issue" -- 5.0-3610. Get: "Error - Second build cannot be less than or equal to the first."

Okay, so i reverse them. Program accepts the numbers. But then it keeps testing in the range where the bug is already confirmed. (E.g., program tests 5.0-3000. Bug occurs? Yes. Then program tests 5.0-3300. It should be testing between 2690 and 3000 at that step.) It just keeps pulling confirmed buggy builds like 3400, 3500, etc..

**Comment by Helios747** [comment]
This would be a great case of me not properly testing my releases :)

When I redid the buildlist, I changed the indexing order of how the builds were placed into the list. I forgot to switch the logic in code so things get... Messy. I'm working on this, as well as correcting the UI.

**Comment by jvook** [comment]
Yes that sounds like a pain-in-the-butt.  Thanks

**Comment by Helios747** [comment]
Fixed in https://github.com/Helios747/DolphinBisectTool/releases/tag/v1.1.1

Closed. Thanks for reporting!
