### ISSUE TITLE
Boot title fails after first run

### ISSUE THREAD

**Issue by jvook** [Helios747/DolphinBisectTool#14]
For the first run Boot Title option will work.  Afterwards, it produces error: "The specified file "/b" does not exist" when selecting to Start.  Then Dolphin resorts to loading the usual title list.  If its relevant this in the build range of 5.0-2000 to 5.0-4000.  It's possible the /b option is just broken in those builds but I don't think so.

**Comment by Helios747** [comment]
That would be because we changed functionality of the boot option in 5.0-2000ish onwards.


I'll try to think of a solution for this.

**Comment by Helios747** [comment]
fixed in latest release
