### ISSUE TITLE
[Improvement] Generate log file of testing results

### ISSUE THREAD

**Issue by jvook** [Helios747/DolphinBisectTool#15]
When testing is interrupted for any reason, it can be hard to determine which versions have been successfully tested and what the progress of the bisect is.  A simple text log file showing build numbers and the user's selected result would make it easier to continue testing in the event the bisect is unexpectedly terminated early.

**Comment by Helios747** [comment]
Good idea, I like it!

I'll implement that in the next feature release.

**Comment by Helios747** [comment]
Implemented in https://github.com/Helios747/DolphinBisectTool/commit/ed7f54d5048e94c5c99faea237e715b67221b9fa

Thanks for the awesome idea!
