### ISSUE TITLE
Failure if the build download doesn't exist

### ISSUE THREAD

**Issue by Techjar** [Helios747/DolphinBisectTool#16]
It spits out an error when extracting the archive and I cannot continue bisecting. This can happen if the Windows build failed and doesn't exist ([5.0-2409](https://dolphin-emu.org/download/dev/7b3b8f26a3f97c01eefc1e596e17be391245a3e5/) is one such case), so this would need to be properly handled by falling back to another build.

**Comment by Helios747** [comment]
So, I'm implementing a workaround for this but it's... not great.

Basically, I'll have it not fail if it can't download the build, but, this also means that there will be untestable builds with DBT, particularly problematic of *one of those builds is the culprit*

So, to notify the user of this, I will just have it throw a dialog saying that it could not download the build and that the bisect may end up being invalid, and at the end, have it show which builds it skipped so the user can manually go investigate.

I intend on fixing this when I implement logging in the next feature release

**Comment by Techjar** [comment]
It may not be great, but I can't see a better way to do it, being that the build is just outright untestable. It's certainly better than having the bisecting fail entirely, which is particularly unhelpful.

**Comment by Helios747** [comment]
Fixed in https://github.com/Helios747/DolphinBisectTool/commit/d41d25e4977863a1d1acbf172addf875a6c06607

hopefully. releasing an update now.
