### ISSUE TITLE
DBT-downloaded builds all identify themselves as 4.0.2 - is it normal?

### ISSUE THREAD

**Issue by ajburley** [Helios747/DolphinBisectTool#6]
Every build that DBT downloads is marked "4.0.2" in the title bar and Help->About displays the commit hash as ...c3d4f and compiled on Nov 29 2013. Is this expected behaviour?? I feel worried that every single build downloaded by DBT is actually the stable 4.0.2, even though DBT "thinks" they are development builds.

**Comment by Helios747** [comment]
I'll look into this when I get home.

**Comment by ajburley** [comment]
Capturing some data here for a test run with first = 4.0-0 and last = 4.0-9511.

`1.` To start with, the Dolphin version from a previous build (from when I ran DBT yesterday) was present

"Dolphin.Bisect.Tool\dolphin.7z"
size = 5286110
created = 15 ‎August ‎2016, ‏‎10:27:10
modified = 15 ‎August ‎2016, ‏‎10:35:12

"Dolphin.Bisect.Tool\dolphin\Dolphin-x64\Dolphin.exe"
size = 15587752
created = 24 ‎June ‎2016, ‏‎11:00:01
modified = 24 ‎June ‎2016, ‏‎11:00:01

`2.` After clicking Start, the Dolphin folder got deleted (as expected) and then re-created

`3.` After Dolphin launched:

"Dolphin.Bisect.Tool\dolphin.7z"
size = 4925105
created = 15 ‎August ‎2016, ‏‎10:27:10
modified = 16 ‎August ‎2016, ‏‎01:52:32

"Dolphin.Bisect.Tool\dolphin\Dolphin-x64\Dolphin.exe"
size = 13131776
created = 04 ‎December ‎2014, ‏‎02:11:17
modified = ‎04 ‎December ‎2014, ‏‎02:11:17

`4.` What the Dolphin that launched reports internally:

Dolphin 4.0.2
Copyright (c) 2003-2013+ Dolphin Team

Branch: master
Revision: 2879...3d4f (I'm not going to type out the whole thing)
Compiled: Nov 29 2013 @ 21:11:19

`5.` What is reported in Task Manager:

Strangely, Task Manager reports that the Dolphin.exe running is actually my installed Dolphin instance, which is at "C:\Program Files\Dolphin402\Dolphin.exe". **This could be the actual issue, but that doesn't explain why this is happening.**

`6.` After closing Dolphin:

DBT says:

```
---------------------------
Bisect
---------------------------
Tested build 4.0-4465. Did the bug happen in this build?
---------------------------
Yes   No   Cancel   
---------------------------
```

It seems DBT "thinks" that build 4.0-4465 was running, even though it wasn't.

`7.` After clicking Cancel and closing DBT, started Dolphin from "Dolphin.Bisect.Tool\dolphin\Dolphin-x64\Dolphin.exe".

Dolphin reports 4.0-4465 in the title bar. This confirms once and for all that (a) DBT did download the correct version, (b) the version started by DBT was not actually the version it downloaded (as they have different title bar versions).

**Comment by ajburley** [comment]
If I go to Start -> Run and type "Dolphin.exe" it runs Dolphin 4.0.2. So it seems somehow the `runner.StartInfo.WorkingDirectory` in [RunBuild.cs](https://github.com/Helios747/DolphinBisectTool/blob/master/DolphinBisectTool/RunBuild.cs) is getting ignored.

PS: My .NET 4.0 version is 4.0.30319, in case that helps? (I am not sure if the .NET API itself changed or something like that.)

**Comment by ajburley** [comment]
PS: My .NET 4.0 version is 4.0.30319, in case that helps? (I am not sure if the .NET API itself changed or something like that.)

**Comment by ajburley** [comment]
`7.` After clicking Cancel and closing DBT, started Dolphin from "Dolphin.Bisect.Tool\dolphin\Dolphin-x64\Dolphin.exe".

Dolphin reports 4.0-4465 in the title bar. This confirms once and for all that (a) DBT did download the correct version, (b) the version started by DBT was not actually the version it downloaded (as they have different title bar versions).

**Comment by Helios747** [comment]
Wow. Thanks for pinning this down. I couldn't reproduce this and was scratching my head on what could be happening.

I'll rework runbuild.cs this weekend when I'm not distracted by other things. I'll just rig up something to force the process starter to be more explicit with pathing. Interesting that it's being ignored.

**Comment by ajburley** [comment]
Hi, this very simple PR fixed the issue for me: https://github.com/Helios747/DolphinBisectTool/pull/7

Can you merge it and do a release?

**Comment by ajburley** [comment]
PS: #7 now conforms to naming convention; sorry I missed it the first time
